### ISSUE TITLE
"Cannot reach management server" error and DeveloperDoesNotExist exception in logs

### ISSUE THREAD

**Issue by jbennett13** [apigee/apigee-edge-drupal#115] opened 2019-01-18 21:50 UTC
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | yes
| New Feature?                | no
| Module Version              | dev branch
| PHP Client version          | 7.1.25
| Requires PHP client fix     | no|link to an Apigee Client PHP library issue or pull request

#### Actual Behavior

What is the actual behavior?

I was able successfully connect to Apigee Edge after completing a fresh install of the Apigee Developer Portal Kickstart module.  however, when I click on "My Apps", the connection fails and  I get the following error in  the log files:

```Drupal\apigee_edge\Exception\DeveloperDoesNotExistException: Developer with [email] email address not found. in Drupal\apigee_edge\Entity\ListBuilder\DeveloperAppListBuilderForDeveloper->checkDeveloperStatus() (line 48 of /app/web/modules/contrib/apigee_edge/src/Entity/DeveloperStatusCheckTrait.php).```

#### Expected Behavior

What is the behavior you expect?

I expect to see a list of apps associated with the product.

#### Proposed Solution

Although I was listed as an org administrator for the org I was connecting to, I had not been added as a Developer.  Manually adding myself as a developer to the org fixed the problem.  A developer sync through the Drupal admin might fix it as well.

**Comment by cnovak** [comment] 2019-01-18 23:48
When a user registers on the Drupal site, a corresponding developer record is created in Apigee Edge so that the apps can be displayed for that user.  However, you can run into this issue when you configure the Apigee Edge Drupal module on a Drupal site that already has users that do not exist as developers in Apigee Edge.  

If you are logged into your Drupal site with a user that is not a developer in Edge, you will see the following message when trying to display the user's apps: `Cannot reach management server. An administrator should check the configuration of this site.`

This message is confusing since the management server is configured properly and is able to reach the Apigee Edge management server, the actual issue is that the developer is not found in Apigee Edge.

#### Workarounds
1. Run the Apigee Edge module's developer sync, which will make sure all users in your Drupal site have corresponding developer entities created in Apigee Edge.
2. Manually create a developer in Apigee Edge with the same email address as the user in Drupal.

#### Proposed solution
If the Drupal module tries to get a developer from Edge and the response returned is that the developer does not exist, immediately create the corresponding developer from the logged in Drupal user data.  In this situation, when going to the "My Apps" page you will be displayed with an empty app list instead of an error.

**Comment by mxr576** [comment] 2019-01-21 09:19
> However, you can run into this issue when you configure the Apigee Edge Drupal module on a Drupal site that already has users that do not exist as developers in Apigee Edge.

This is true and I thought we have already documented that [running developer sync](https://www.drupal.org/docs/8/modules/apigee-edge/synchronize-developers-with-apigee-edge) is a **required step** after the Apigee Edge connection gets configured (or even when the connected Apigee Edge organization gets changed in a configured Drupal site), but I haven't found anything regarding this in [Configure the connection to Apigee Edge](https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge). (Could you please add this missing step @llynch00?)

> If you are logged into your Drupal site with a user that is not a developer in Edge, you will see the following message when trying to display the user's apps: Cannot reach management server. An administrator should check the configuration of this site.
> This message is confusing since the management server is configured properly and is able to reach the Apigee Edge management server, the actual issue is that the developer is not found in Apigee Edge.

This is the default _general_ error message that we display to all users when any kind of API communication issue occurs. This can be changed as it is written in the [documentation](https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge#configuring-error-handling-for-a-failed-connection). So I do not think that there is an issue with this.

> If the Drupal module tries to get a developer from Edge and the response returned is that the developer does not exist, immediately create the corresponding developer from the logged in Drupal user data.

I do not like this idea because of multiple reasons. First of all, a missing developer for a Drupal user is clearly a sign of an error that should require a manual investigation and a fix. (If the system is configured properly and nobody forgot to run the initial developer sync when the connection to Apigee Edge has been configured.) The reason why a Drupal user does not have developer on Apigee Edge should be investigated by using log entries in Drupal. Drupal does not allow creation of a Drupal user if the related [create developer](https://apidocs.apigee.com/management/apis/post/organizations/%7Borg_name%7D/developers) API call fails on Apigee Edge so in general, if a Drupal user could exist in Drupal without a developer in Apigee Edge could be because of a:
* User error: Someone forgot to run the developer sync when the connection to an Apigee Edge organization got configured.
* System error: The validation meanwhile the Drupal user creation does not work as it should be and it requires a manual fix.
* Workflow error: Someone deleted a Drupal user's developer account on Apigee Edge, although s/he should have deleted that in Drupal or should have just [deactivated the developer/user](https://www.drupal.org/docs/8/modules/apigee-edge/deactivate-developers).

Automatic creation of a missing developer on Apigee Edge programmatically is also not a good idea because:
* We would need to check and ensure the existence of a developer in all page requests that would increase the number of API calls that we try to keep in minimum for performance reasons.
* We would need to run this check in the very beginning of each page requests otherwise previous code parts that have been executed before the creation of the missing developer could still fail... (The error that you experienced has been throw in the page build phase, which is almost the last step of the response generation for a request. Before that the route resolve, access check and a bunch of other subsystem of Drupal gets executed.)

### Proposed solutions

#### Apigee Developer Portal Kickstart project

1. Expose the Apigee Edge connection configuration form as an installation process step
Similarly what we had in Drupal 7 distribution. The Apigee Edge connection must be configured before the admin user would have been created meanwhile the installation process. That would also require the setup of the Private files folder.
2. Display a simple warning message to the admin user (uid1) after the installation process has finished that Apigee Edge connection must be configured and **developer synchronization must executed** after the configuration has been saved.

#### Apigee Edge module

Developer status trait - that thrown the error in the page build phase - has been deprecated, although the same error gets thrown now even one layer before but within the same phase of response generation.
`Developer with testelek@example.com email address not found. Drupal\apigee_edge\Entity\ListBuilder\DeveloperAppListBuilderForDeveloper->buildEntityIdQuery()`. As you can we have documented in place that this is the expected reaction in this situation: https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.x/src/Entity/ListBuilder/DeveloperAppListBuilderForDeveloper.php#L123
Admins can see the reason of the error in the logs:
![image](https://user-images.githubusercontent.com/1755573/51462935-28cc7800-1d62-11e9-82d5-5102eb695c5f.png)

I am not sure what we can improve here. As I described above this issue is clearly a sign of an error that should require a manual a fix. Catching this exception and displaying an empty list of apps on the My apps to a user when an issue like this occurs would be misleading and disturbing. Especially if the user knows that s/he had apps before this error occurred. If the user is new and s/he can access to the Add app form (because s/he can see it on the empty My apps page) and s/he tries to create an app s/he is going to face with an error because s/he can not create an app without having a developer in Apigee Edge.
Revoking the access to the My apps page when this problem occurs also would not be a good idea because new users who does not know the UI would not realize that there is a problem. At this moment at least they can at least see the error message with an instruction to reach the administrators because there is an issue with his/her account.

What we could do improve is on the connection configuration form. We could add a warning message that developer sync should be executed if the connection is configured for the first time or the connected organization gets changed. So even if someone does not read the documentation s/he can see a warning about a required step that could read to potential errors in the future.

**Comment by cnovak** [comment] 2019-01-24 14:02
I would think there would be a way for us to catch an exception when a developer does not exist and add current user if this error is thrown. 

However,  an easy fix would be to change the incorrect error message "Cannot reach management server" when a developer account is not found to display "Developer not found".   When @jbennett13 first reported this error it was due to this misleading message of "Cannot reach management server", they were trying to fix the issue by modifying and reverifying the Edge connection settings and could not figure out what was wrong since they did not realize the logs would have the correct error message.

**Comment by mxr576** [comment] 2019-01-24 19:42
@cnovak  I think you are focusing on the wrong problem. The problem is not the general API communication error message that we display to all users as a "Something went wrong" page. Administrators can see detailed log messages about events that triggered a "Connection error" page redirections in the logs. (I think we already have a documentation about [how to access logs generated by this module on a vanilla Drupal installation](https://www.drupal.org/docs/8/core/modules/dblog/overview), aren't we?) I think this is a documentation/workflow issue and the Apigee Edge module's [connection configuration form](https://www.drupal.org/docs/8/modules/apigee-edge/configure-the-connection-to-apigee-edge) and the Kickstarter installer should guide users to the right directions when they are installing the module for the first time.

We ensured that if the Apigee Edge module is enabled and someone tries to create a user in Drupal the user only gets created if the module could create its developer account on Apigee Edge first. Consequently, there are were few cases when it could happen that a Drupal user gets a "Connection error" page, because it does not have a developer account on Apigee Edge:

1. Who configured the Apigee Edge connection forgot to run the developer synchronization. As I wrote earlier, even when connected Apigee Edge organization gets changed on a configured site the developer should be executed - either automatically, or by a user manually - to ensure the two system (Drupal and Apigee Edge) are in sync, meaning all Drupal users has a developer account in Apigee Edge and vica-versa.
This point also covers @jbennett13 problem. The Kickstart's installer either should have allowed her to configure the Apigee Edge connection before she finalized the installation of Drupal and created the first user (uid1) on the site or it should have warned with an error message that the she won't be able to use the Apigee Edge features until she has not configured the Apigee Edge connection and ran the developer sync after the installer finished.
Fun fact. The very same issue _still_ exists in the Drupal 7 distribution. The admin user (uid1) which email is noreply@apigee.com does not have a developer account in Apigee Edge. Thanks to this it gets either Access denied or an error when it visits it's My apps page, I do not remember which one. What I am trying to say that ideally the install profile should create a developer account to the first Drupal user when Drupal is installed.

2. Someone deletes developer accounts on Apigee Edge instead of using Drupal's UI (ex.: by using the MGTM UI). Well, it is not a recommended workflow but it can be used. Although, in this case they should setup a cron job to execute the developer sync periodically in the background by using the Drush command that the module provides.

```
$ drush | grep apigee
   apigee-edge:sync                               Developer synchronization.  
```

Do you see any problem with my proposed solutions in this comment and in my previous comment @cnovak?

**Comment by cnovak** [comment] 2019-01-25 19:52
It is not clear from the initial issue description, but the user was confused by the error message and kept going back to the configuration settings page to try to figure out why they are getting a "Cannot reach management server" error on the site.  It wasn't clear to them until I explained to them to check the logs what the real issue was. 

Your solutions sound great for production setups.  However, we should strive to make initial setup and evaluation easy for anyone using the module.

**Comment by mxr576** [comment] 2019-01-26 07:12
Should we change the default connection error message? Would that help?
Although, even if we change that it still needs to  be documented how an administrator can investigate bug reports that says the user was redirected to this error page. Who are not familiar with Drupal they definitely won't know how to investigate runtime errors like this. The connection error page is still better than a the default WSOD (white screen of death) page that Drupal provides because at least it makes it clear that the problem is around the Apigee Edge module.
If we start displaying custom error messages for http code >= 400 and < 600 errors for users, why would we stop on the developer does not exist error?
An API response does contain an error code which looks like a constant, but I am not sure whether it is a constant or not. If it does not we can not build a condition to catch that.
We could display the exact error code and/or error message on this page, so without any custom error handling, the user would see what was the reason of the failure according to the API. Although I am not sure whether we would like to do that. Those strings are never going to be translatable in Drupal and they may expose too much information to a simple user.
ex.:
```json
{
  "code": "developer.service.DeveloperIdDoesNotExist",
  "message": "DeveloperId test@example.com does not exist in organization Test",
  "contexts": []
}
```

**Comment by mxr576** [comment] 2019-05-07 06:22
@cnovak Do we have or need a JIRA issue for this that we can schedule for a sprint or can we close this GH issue with won't fix?

**Comment by cnovak** [comment] 2019-05-08 18:49
Our goal is to reduce issues and confusion when users are first setting up this module. We will look into this after other urgent issues are fixed.

**Comment by mxr576** [comment] 2019-06-04 05:24
@arunz6161 @cnovak FYI, we have just bumped into this problem again on a customer project. It would be great if we would display a warning message at least if the connection settings are changes (or configured for the first time) the user must run the developer sync. I could work on this task in the next sprint.

**Comment by shadcn** [comment] 2019-06-17 11:05
@mxr576 are you working on this in https://github.com/apigee/apigee-edge-drupal/issues/221?

**Comment by mxr576** [comment] 2019-06-17 11:21
@arshad I have some ideas and plans in my head how this could be solved but I have not got a green light from @arunz6161 to work on this in this sprint. I hope this may change after the sprint planning tomorrow.

**Comment by shadcn** [comment] 2019-06-18 12:29
I created PR https://github.com/apigee/apigee-edge-drupal/pull/227 with a proposed solution.

**Closed as completed** 2019-06-20 05:02 UTC
