### ISSUE TITLE
[Hybrid] Connection Error when Deleting App

### ISSUE THREAD

**Issue by Shanli-Yu** [apigee/apigee-edge-drupal#312] opened 2019-12-16 23:03 UTC
**EDIT**: This issue only occurs when kickstart is connected to hybrid using devadmin service account. If service account has orgadmin role, this issue does not occur

**Describe the bug**
When deleting an app, a “Connection error” will appear 

**To Reproduce**
1. Go to 'Apps' page
2. Click on an existing app
3. Click on "Delete"

**Expected behavior**
A message should appear asking the user for delete confirmation by typing the name of the app. 

**Screenshots**
![image](https://user-images.githubusercontent.com/45441018/70950044-4f4b6f80-2014-11ea-833b-2c9c722d9149.png)
Then
![image](https://user-images.githubusercontent.com/45441018/70950061-596d6e00-2014-11ea-8acb-5d487b2f8cfa.png)

**Additional context**
Once site cache is cleared and immediately visit the app delete page, the confirmation page will appear and typing the name of app will delete the app, but if page was refreshed, or any other pages were visited between cache clear and visiting the delete page, the error will reappear and delete will no longer work. 

Below is additional Watchdog logs
`PERMISSION_DENIED: The caller does not have permission Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->decodeResponse() (line 104 of /app/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/ResponseHandlerPlugin.php).
#0 /app/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/ResponseHandlerPlugin.php(69): Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->decodeResponse(Object(GuzzleHttp\Psr7\Response), Object(GuzzleHttp\Psr7\Request))
#1 /app/vendor/php-http/httplug/src/Promise/HttpRejectedPromise.php(33): Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->Apigee\Edge\HttpClient\Plugin\{closure}(Object(Http\Client\Exception\HttpException))
#2 /app/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/ResponseHandlerPlugin.php(75): Http\Client\Promise\HttpRejectedPromise->then(Object(Closure), Object(Closure))
#3 /app/vendor/php-http/client-common/src/PluginClient.php(161): Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#4 /app/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/RetryOauthAuthenticationPlugin.php(57): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#5 /app/vendor/php-http/client-common/src/PluginClient.php(161): Apigee\Edge\HttpClient\Plugin\RetryOauthAuthenticationPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#6 /app/vendor/php-http/client-common/src/Plugin/HistoryPlugin.php(39): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#7 /app/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HistoryPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#8 /app/vendor/php-http/client-common/src/Plugin/AuthenticationPlugin.php(36): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#9 /app/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\AuthenticationPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#10 /app/vendor/php-http/client-common/src/Plugin/HeaderDefaultsPlugin.php(41): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#11 /app/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\HeaderDefaultsPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#12 /app/vendor/apigee/apigee-client-php/src/HttpClient/Plugin/AddPathPlugin.php(78): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#13 /app/vendor/php-http/client-common/src/PluginClient.php(161): Apigee\Edge\HttpClient\Plugin\AddPathPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#14 /app/vendor/php-http/client-common/src/Plugin/AddHostPlugin.php(64): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#15 /app/vendor/php-http/client-common/src/PluginClient.php(161): Http\Client\Common\Plugin\AddHostPlugin->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#16 /app/vendor/php-http/client-common/src/PluginClient.php(175): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#17 /app/vendor/php-http/client-common/src/PluginClient.php(88): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Request))
#18 /app/vendor/apigee/apigee-client-php/src/Client.php(242): Http\Client\Common\PluginClient->sendRequest(Object(GuzzleHttp\Psr7\Request))
#19 /app/vendor/apigee/apigee-client-php/src/Client.php(390): Apigee\Edge\Client->sendRequest(Object(GuzzleHttp\Psr7\Request))
#20 /app/vendor/apigee/apigee-client-php/src/Client.php(194): Apigee\Edge\Client->send('GET', Object(GuzzleHttp\Psr7\Uri), Array, NULL)
#21 /app/vendor/apigee/apigee-client-php/src/Api/Management/Controller/AppController.php(66): Apigee\Edge\Client->get(Object(GuzzleHttp\Psr7\Uri))
#22 /app/web/modules/contrib/apigee_edge/src/Entity/Controller/AppController.php(105): Apigee\Edge\Api\Management\Controller\AppController->loadApp('7a2aa5bd-9aad-4...')
#23 /app/web/modules/contrib/apigee_edge/src/Entity/Controller/DeveloperAppEdgeEntityControllerProxy.php(80): Drupal\apigee_edge\Entity\Controller\AppController->loadApp('7a2aa5bd-9aad-4...')
#24 /app/web/modules/contrib/apigee_edge/src/Entity/Storage/AppStorage.php(91): Drupal\apigee_edge\Entity\Controller\DeveloperAppEdgeEntityControllerProxy->load('7a2aa5bd-9aad-4...')
#25 /app/web/modules/contrib/apigee_edge/src/ParamConverter/DeveloperAppNameConverter.php(90): Drupal\apigee_edge\Entity\Storage\AppStorage->loadUnchanged('7a2aa5bd-9aad-4...')
#26 /app/web/core/lib/Drupal/Core/ParamConverter/ParamConverterManager.php(100): Drupal\apigee_edge\ParamConverter\DeveloperAppNameConverter->convert('shanlitest', Array, 'app', Array)
#27 /app/web/core/lib/Drupal/Core/Access/AccessManager.php(89): Drupal\Core\ParamConverter\ParamConverterManager->convert(Array)
#28 /app/web/core/lib/Drupal/Core/Menu/LocalTaskManager.php(347): Drupal\Core\Access\AccessManager->checkNamedRoute('entity.develope...', Array, Object(Drupal\Core\Session\AccountProxy), true)
#29 /app/web/core/lib/Drupal/Core/Menu/LocalTaskManager.php(378): Drupal\Core\Menu\LocalTaskManager->getTasksBuild('entity.develope...', Object(Drupal\Core\Cache\CacheableMetadata))
#30 /app/web/core/lib/Drupal/Core/Menu/Plugin/Block/LocalTasksBlock.php(95): Drupal\Core\Menu\LocalTaskManager->getLocalTasks('entity.develope...', 0)
#31 /app/web/core/modules/block/src/BlockViewBuilder.php(163): Drupal\Core\Menu\Plugin\Block\LocalTasksBlock->build()
#32 [internal function]: Drupal\block\BlockViewBuilder::preRender(Array)
#33 /app/web/core/lib/Drupal/Core/Render/Renderer.php(378): call_user_func('Drupal\\block\\Bl...', Array)
#34 /app/web/core/lib/Drupal/Core/Render/Renderer.php(450): Drupal\Core\Render\Renderer->doRender(Array)
#35 /app/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#36 /app/web/core/lib/Drupal/Core/Template/TwigExtension.php(601): Drupal\Core\Render\Renderer->render(Array)
#37 /app/web/sites/default/files/php/twig/5df804db2fbc6_page.html.twig_DCLQr6-jTnExda0wg7dYwDKN5/oUi9s8QpVEO0o6I0e60BY1r6qO0vV37e13liMoEqNKA.php(135): Drupal\Core\Template\TwigExtension->renderVar(Array)
#38 /app/vendor/twig/twig/src/Template.php(455): __TwigTemplate_83f4fdfeca6a68a0abc9c203a1bdab94c9a60afd125feb1638ae1bfece7ad33f->doDisplay(Array, Array)
#39 /app/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#40 /app/web/sites/default/files/php/twig/5df804db2fbc6_page--user.html.twig_R3zPSzkQCiB8yfM6a9Htdia3s/Dhb3blljK3-X3c5O2jxkS_MlH56B8h58YPUqZUAwa0I.php(55): Twig\Template->display(Array)
#41 /app/vendor/twig/twig/src/Template.php(455): __TwigTemplate_bf41969bdcb8a40d2d5efca7bc72aa328b01276b830a83c8d0edf4a97c241953->doDisplay(Array, Array)
#42 /app/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#43 /app/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
#44 /app/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#45 /app/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/contri...', Array)
#46 /app/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('page', Array)
#47 /app/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#48 /app/web/core/lib/Drupal/Core/Template/TwigExtension.php(501): Drupal\Core\Render\Renderer->render(Array)
#49 /app/web/sites/default/files/php/twig/5df804db2fbc6_html.html.twig_FBnTNTNzgwmC1BHIB6UgCwKPV/nuOmDG--HNK4bFXG103GP6wOuB887OUkWdIC0jQRsEw.php(101): Drupal\Core\Template\TwigExtension->escapeFilter(Object(Drupal\Core\Template\TwigEnvironment), Array, 'html', NULL, true)
#50 /app/vendor/twig/twig/src/Template.php(455): __TwigTemplate_8b9ee55c8194d29488d9a2f0dcfb6430c3b066db5a44273f86fb06151fd919d0->doDisplay(Array, Array)
#51 /app/vendor/twig/twig/src/Template.php(422): Twig\Template->displayWithErrorHandling(Array, Array)
#52 /app/vendor/twig/twig/src/Template.php(434): Twig\Template->display(Array)
#53 /app/web/core/themes/engines/twig/twig.engine(64): Twig\Template->render(Array)
#54 /app/web/core/lib/Drupal/Core/Theme/ThemeManager.php(384): twig_render_template('profiles/contri...', Array)
#55 /app/web/core/lib/Drupal/Core/Render/Renderer.php(437): Drupal\Core\Theme\ThemeManager->render('html', Array)
#56 /app/web/core/lib/Drupal/Core/Render/Renderer.php(195): Drupal\Core\Render\Renderer->doRender(Array, false)
#57 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(147): Drupal\Core\Render\Renderer->render(Array)
#58 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}()
#59 /app/web/core/lib/Drupal/Core/Render/MainContent/HtmlRenderer.php(148): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure))
#60 /app/web/core/lib/Drupal/Core/EventSubscriber/MainContentViewSubscriber.php(90): Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object(Symfony\Component\HttpFoundation\Request), Object(Drupal\Core\Routing\CurrentRouteMatch))
#61 [internal function]: Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#62 /app/web/core/lib/Drupal/Component/EventDispatcher/ContainerAwareEventDispatcher.php(111): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent), 'kernel.view', Object(Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher))
#63 /app/vendor/symfony/http-kernel/HttpKernel.php(156): Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object(Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent))
#64 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#65 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#66 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#67 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#68 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#69 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#70 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#71 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#72 /app/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#73 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request))
#74 {main}`

**Comment by Shanli-Yu** [comment] 2019-12-16 23:19
When attempting to delete the app right after cache clear, the app will be deleted and will have below watchdog error: 
`TypeError: Argument 1 passed to Apigee\Edge\Api\Management\Controller\AppByOwnerController::responseArrayToArrayOfEntities() must be of the type array, boolean given, called in /app/vendor/apigee/apigee-client-php/src/Controller/NonPaginatedEntityListingControllerTrait.php on line 47 in Apigee\Edge\Api\Management\Controller\AppByOwnerController->responseArrayToArrayOfEntities() (line 42 of /app/vendor/apigee/apigee-client-php/src/Controller/EntityListingControllerTrait.php) #0 /app/vendor/apigee/apigee-client-php/src/Controller/NonPaginatedEntityListingControllerTrait.php(47): Apigee\Edge\Api\Management\Controller\AppByOwnerController->responseArrayToArrayOfEntities(false) #1 /app/web/modules/contrib/apigee_edge/src/Entity/Controller/AppByOwnerController.php(127): Apigee\Edge\Api\Management\Controller\AppByOwnerController->getEntities() #2 /app/web/modules/contrib/apigee_edge/src/Entity/Query/AppQueryBase.php(196): Drupal\apigee_edge\Entity\Controller\AppByOwnerController->getEntities() #3 /app/web/modules/contrib/apigee_edge/src/Entity/Query/Query.php(86): Drupal\apigee_edge\Entity\Query\AppQueryBase->getFromStorage() #4 /app/web/modules/contrib/apigee_edge/src/Entity/ListBuilder/EdgeEntityListBuilder.php(71): Drupal\apigee_edge\Entity\Query\Query->execute() #5 /app/web/core/lib/Drupal/Core/Entity/EntityListBuilder.php(86): Drupal\apigee_edge\Entity\ListBuilder\EdgeEntityListBuilder->getEntityIds() #6 /app/web/profiles/contrib/apigee_devportal_kickstart/modules/custom/apigee_kickstart_enhancement/src/Entity/ListBuilder/DeveloperAppListBuilder.php(35): Drupal\Core\Entity\EntityListBuilder->load() #7 [internal function]: Drupal\apigee_kickstart_enhancement\Entity\ListBuilder\DeveloperAppListBuilder->render() #8 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(123): call_user_func_array(Array, Array) #9 /app/web/core/lib/Drupal/Core/Render/Renderer.php(582): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #10 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(124): Drupal\Core\Render\Renderer->executeInRenderContext(Object(Drupal\Core\Render\RenderContext), Object(Closure)) #11 /app/web/core/lib/Drupal/Core/EventSubscriber/EarlyRenderingControllerWrapperSubscriber.php(97): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->wrapControllerExecutionInRenderContext(Array, Array) #12 /app/vendor/symfony/http-kernel/HttpKernel.php(151): Drupal\Core\EventSubscriber\EarlyRenderingControllerWrapperSubscriber->Drupal\Core\EventSubscriber\{closure}() #13 /app/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #14 /app/web/core/lib/Drupal/Core/StackMiddleware/Session.php(57): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #15 /app/web/core/lib/Drupal/Core/StackMiddleware/KernelPreHandle.php(47): Drupal\Core\StackMiddleware\Session->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #16 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(106): Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #17 /app/web/core/modules/page_cache/src/StackMiddleware/PageCache.php(85): Drupal\page_cache\StackMiddleware\PageCache->pass(Object(Symfony\Component\HttpFoundation\Request), 1, true) #18 /app/web/core/lib/Drupal/Core/StackMiddleware/ReverseProxyMiddleware.php(47): Drupal\page_cache\StackMiddleware\PageCache->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #19 /app/web/core/lib/Drupal/Core/StackMiddleware/NegotiationMiddleware.php(52): Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #20 /app/vendor/stack/builder/src/Stack/StackedHttpKernel.php(23): Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #21 /app/web/core/lib/Drupal/Core/DrupalKernel.php(693): Stack\StackedHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #22 /app/web/index.php(19): Drupal\Core\DrupalKernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #23 {main}.`

**Comment by Shanli-Yu** [comment] 2019-12-16 23:49
Identical error message will occur when trying to edit the app: 
![image](https://user-images.githubusercontent.com/45441018/70952566-748fac00-201b-11ea-9e2a-49e9fdf145b8.png)
"-----------------------------------------------------------------"
![image](https://user-images.githubusercontent.com/45441018/70952591-8cffc680-201b-11ea-9b72-8d78f35ed92e.png)

**Comment by phdhiren** [comment] 2020-12-29 10:09
@Shanli-Yu , I could not reproduce the error mentioned with latest build. Are you still facing the issue?

**Comment by phdhiren** [comment] 2021-01-11 09:08
@Shanli-Yu, Feel free to reopen, if you still face the issue. Closing for now.

**Closed as completed by phdhiren** 2021-01-11 09:08 UTC
Labels: bug, help wanted, hybrid
