### ISSUE TITLE
Opening a Team invitation shows Access Denied if user is not logged in

### ISSUE THREAD

**Issue by mukhan-23** [apigee/apigee-edge-drupal#580] opened 2021-04-26 18:51 UTC
## Description
When a user receives a Team invitation, if they are not logged in, they immediately get an 'Access Denied' page. They should be redirected to login if they are an anonymous user.

## Steps to Reproduce
Send a Team invitation. Open team invitation in incognitio window

## Actual Behavior
Access Denied Error

## Expected Behavior
User redirected to login if they are anonymous

**Comment by phdhiren** [comment] 2021-04-27 04:26
Duplicate of #570

**Comment by phdhiren** [comment] 2021-04-28 04:24
This has been resolved with the pull #570

**Closed as completed by phdhiren** 2021-04-28 04:24 UTC
Labels: bug, apigee_edge_teams
