### ISSUE TITLE
API product RBAC module ignores access control for team apps

### ISSUE THREAD

**Issue by kbrinner** [apigee/apigee-edge-drupal#246] opened 2019-08-05 21:33 UTC
This isn't necessarily a bug per-se, but I was a little surprised by this when I first experienced it. It might be as simple as adding a message on the admin/config/apigee-edge/developer-settings/access-control config page reminding admins that these RBACs are only enforced for developer apps. 

**Description**
As a user, I am able to essentially bypass any role-based access control configured in the API Product RBAC submodule when creating a team app. RBAC works fine for developer apps, but is not enforced when the user creates a team app. 

**To Reproduce**
1. Configure API Product RBAC so only a few products are available to authenticated users.
2. As an authenticated user, create a developer app. Only those few products configured in step 1 will be available when creating an app.
3. As an authenticated user, create a team app. All products are now available to the user when creating the team app. 

**Expected behavior**
I did expect the RBAC to be enforced for the user when creating the team app. However on second thought that is not necessarily what people might want - they might want team-based access control or some other level of control like that, so probably wouldn't want to assume RBAC be enforced when creating a team app. 

Like I said above, it might be best to simply add an alert to give admins a heads up when configuring API Product RBAC that it is only enforced for developer apps. Like you have already added a notice when configure RBAC that access by visibility is disabled by the RBAC module. 

<img width="588" alt="add another alert" src="https://user-images.githubusercontent.com/957324/62496430-1feb4300-b796-11e9-9782-a0262153fa6d.png">

**Comment by mxr576** [comment] 2019-08-06 06:07
Yes, it is not a bug, this is expected behavior because this API product access only controls access to an API product based on a developer's Drupal role - because developer is the only available data in the next where it gets called. (Access by visibility also works the same way.)
This is the exact reason why merging #190 was not a good idea because the original implementation moved the API product access under Developer where it belongs. That could prevent this confusion. (cc @cnovak)
Where the team is also available in the context (like team app/edit form) you can control the API product access with a different hook. See: 
https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.0/modules/apigee_edge_teams/apigee_edge_teams.api.php#L58
https://github.com/apigee/apigee-edge-drupal/blob/8.x-1.0/modules/apigee_edge_teams/src/TeamMemberApiProductAccessHandler.php

**Comment by cnovak** [comment] 2019-08-06 15:30
Good idea @kbrinner to at least start with adding info on the admin side that RBAC is not enforced for teams, and we need to add this to documentation.

**Comment by cnovak** [comment] 2019-08-08 22:43
@giteshk and I looked at this and came up with the solution of checking the logged in user's permissions when determining what API products are available to a team.  For example, if I am user `foo@example.com` and I create an app for `companyA`, check the permissions for `foo@example.com` to determine the API products available.

**Comment by mxr576** [comment] 2019-08-09 05:28
There was very good reasoning behind separating developer- and team API product access in Drupal 8. We have learned a lot from our Drupal 7 projects and tried to build something that could solve most use cases by default.
The team API product access controls which API products team members can access if they are a member of a team. This also limits what API products a team and its members can access, for example, can obtain API keys.

>  For example, if I am user foo@example.com and I create an app for companyA, check the permissions for foo@example.com to determine the API products available.

If you would like to apply for developers' (members') API product access on team apps like this the entire UI and the workflow is going to be a mess. Just imagine, different developers have access to different API products. When they create an app they can select from a different set of API products. There won't be a consistent set of API products that all team members have access.

Also, the current implementation covers the case when a developer cannot obtain an API key for an API product as a developer _but_ as a team member it can create one for its team that has access.
If you change it like what you described it won't be possible anymore.

@giteshk It works like Organic Group access worked in Drupal 7 for group contents. As a group member (team member) you can CRUDL different group content (api products) as a simple authenticated user (developer).

It would be easier to rollback the #190 and make a clear distinction on the UI and provide an explanation in the documentation what the developer- and the team API product access controls exactly.

**Comment by arlina-espinoza** [comment] 2019-08-30 16:36
@cnovak and I were talking about this and we think a good (more intuitive) solution could be to follow the user's API product permissions, but if they are looking at a team app, they would have access to view all of the API products the app has. If they tried to edit the app, only the API products they have access would be displayed on the form, and a warning message shown on the form stating that if they modify the products the app would loose access to the missing XYZ products. I'll be double checking to see if this is feasible before pushing a PR.

**Comment by cnovak** [comment] 2020-12-11 18:21
TODO: 
* Create a new ticket to handle warning for now
* Spend more time designing how to handle permissions

**Comment by aparnak123** [comment] 2021-02-03 15:03
Hi Raakesh- Do you have new ticket created for this?
I can be spend sometime designing along with you. Our Fortune client wants RBAC module to control team apps as well.

**Comment by raakesh-blokhra** [comment] 2021-02-03 17:33
Hi @aparnak123 I just did #555  but for now, we will work on adding the warning and we can look into the specifics of letting RBAC enforce permissions for team apps. I will discuss the specifics with @cnovak and add any comments to that ticket. I am closing this ticket for now.

**Comment by raakesh-blokhra** [comment] 2021-02-03 19:24
@aparnak123 we can continue working on this issue. I reopened it. The other issue (#555) will be used for adding the warning, while we can continue the discussion here. Let us know what you have in mind.

**Comment by aparnak123** [comment] 2021-02-11 01:52
Each client has different requirement when it comes to Product access.We can start some generic ones
1)Have a config if if they want to extend role based access control to teams apps.
2)Extend admin functionality to assign each team to have some access to specific list of products.(Few default product to all teams)

**Comment by raakesh-blokhra** [comment] 2021-08-10 15:02
Hi @aparnak123 sorry for the super late response. We got busy with all the other updates. Please let me know if you are still available to work on this. I am closing this issue for now, if you are up for it, please reopen and let's knock it out.

**Closed as completed by raakesh-blokhra** 2021-08-10 15:02 UTC
Labels: bug, documentation

**Comment by sumedhafreshgravity** [comment] 2021-09-28 00:37
@aparnak123 , Our client also has the same requirement to extend role based access control to team apps. To achieve this, I have written a custom module. The features of this module are - 
1] Create a role automatically when team is created.
2] Assign this role automatically to each member of the team when user accepts team invitation.
3] Each team has a  tab where we can provide access control mapping for the role specifically created for the team.
4] Delete the role automatically when team gets deleted.
This flow is working very smooth. My next step is  same as yours - 
1)Have a config if if they want to extend role based access control to teams apps.
2)Extend admin functionality to assign each team to have some access to specific list of products.(Few default product to all teams)
so before working on that, I was wondering that it will be great if  you have already implemented this feature. Can you please share your views?
