### ISSUE TITLE
Cannot add entity reference field type to a team.

### ISSUE THREAD

**Issue by audave** [apigee/apigee-edge-drupal#740] opened 2022-09-14 00:55 UTC
## Description
Cannot add entity reference field type to a team.

## Steps to Reproduce
1. Go to /admin/config/apigee-edge/team-settings/fields
2. Click on: Add Field->new field -> Reference (NOT Dynamic Reference) -> Content
3. Click through default options.
4. Edit an existing team, hit save. 
5. Site will crash, error in logs is 
`Error: Call to a member function getValue() on null in Drupal\Core\Entity\Plugin\Validation\Constraint\ValidReferenceConstraintValidator->validate() (line 128 of /app/web/core/lib/Drupal/Core/Entity/Plugin/Validation/Constraint/ValidReferenceConstraintValidator.php)`

**Comment by shishir-intelli** [comment] 2022-09-14 07:56
@audave 
I followed the above steps  but I am not able to reproduce this issue.
Could you please share with us the output of the command: `composer show`  to investigate further.

**Comment by audave** [comment] 2022-09-15 03:48
**Composer show:**
[composer-show.txt](https://github.com/apigee/apigee-edge-drupal/files/9571576/composer-show.txt)

**Some screenshots from the process.**
![Screen Shot 2022-09-15 at 1 12 34 pm](https://user-images.githubusercontent.com/6018549/190309339-e227eeb2-86a0-453f-87fa-82246eecd4f4.png)
![Screen Shot 2022-09-15 at 1 13 39 pm](https://user-images.githubusercontent.com/6018549/190309371-d482afb8-cd8d-4ffe-92b7-f5de9cd96513.png)

![Screen Shot 2022-09-15 at 1 16 59 pm](https://user-images.githubusercontent.com/6018549/190309444-2639007e-c794-4fda-ad40-69d2f820bde5.png)
![Screen Shot 2022-09-15 at 1 13 48 pm](https://user-images.githubusercontent.com/6018549/190309391-aeed1148-8b18-4772-b4fe-fc05a17b4d31.png)

**The Error messages in dblog.**
![Screen Shot 2022-09-15 at 1 17 33 pm](https://user-images.githubusercontent.com/6018549/190309508-03b54c8f-2e60-4f6d-9b79-6db90190213b.png)
![Screen Shot 2022-09-15 at 1 17 42 pm](https://user-images.githubusercontent.com/6018549/190309544-8706defd-0d1e-4504-9438-c5da89a070ef.png)

**Comment by shishir-intelli** [comment] 2022-09-16 07:19
@audave 
I was able to replicate this issue on a regular Drupal 8/9 instance with `Apigee Edge` module installed, working fine on Drupal `Apigee Developer Portal Kickstart` though.
We are investigating this issue, We will keep you posted on any further update.

**Comment by shishir-intelli** [comment] 2022-11-09 12:04
Hi @audave 
Apologies for the delayed response.

This is the Drupal core entity system issue - https://www.drupal.org/project/drupal/issues/3210319
Similar issue resolved here https://github.com/apigee/apigee-edge-drupal/issues/561 by patch.

Please add this patch https://www.drupal.org/files/issues/2021-04-23/validate-reference-constraint-3210319-3.patch for resolving your teams edit issue for reference entity field.

(Refer https://github.com/apigee/apigee-edge-drupal/issues/561 for adding patch.)
Let me know if you need any further help.

**Comment by shishir-intelli** [comment] 2022-11-15 05:04
Hope the above patch has fixed the issue.
Closing this issue for now, please feel free to reopen if you need any further help.

**Closed as completed by shishir-intelli** 2022-11-15 05:04 UTC
Labels: bug
