### ISSUE TITLE
[Hybrid] Fatal error when trying to edit apigee_edge_connection_default keys.

### ISSUE THREAD

**Issue by shadcn** [apigee/apigee-edge-drupal#298] opened 2019-11-20 06:27 UTC
**Describe the bug**
Fatal error when trying to edit `apigee_edge_connection_default` keys.

**To Reproduce**
1. Install Kickstart with latest hybrid modules: Apigee Edge and PHP client.
2. Go to `admin/config/system/keys/manage/apigee_edge_connection_default`
3. Click Edit.
4. You will see an error.

Logs says: `TypeError: Argument 1 passed to Drupal\Core\Form\FormState::setValues() must be of the type array, null given, called in modules/contrib/apigee_edge/src/Plugin/KeyInput/ApigeeAuthKeyInput.php`

**Expected behavior**
No errors when trying to edit the Apigee connection key via the keys.module UI.

**Comment by shadcn** [comment] 2019-11-20 06:32
Note: This does not happen when a Hybrid key is set.

**Comment by arlina-espinoza** [comment] 2019-11-20 19:37
I haven't been able to reproduce this bug - will keep trying.

**Comment by arunz6161** [comment] 2019-11-20 20:01
Unable to reproduce the issue even after switching to public cloud settings on the config page.

**Comment by arlina-espinoza** [comment] 2019-11-27 21:09
Closing - unable to reproduce.

**Closed as completed by arlina-espinoza** 2019-11-27 21:09 UTC
Labels: bug, hybrid
