### ISSUE TITLE
Team member invitation limit

### ISSUE THREAD

**Issue by varuntit101** [apigee/apigee-edge-drupal#516] opened 2020-11-10 10:25 UTC
## Description
Once a member is invited to a team, until he accepts or rejects the invitation, he can't be added to a second team

## Steps to Reproduce
1. Create a team
2. Add a member to the team. (Do not accept/reject the invitation yet)
3. Create a second team
4. Add the same member to the second team

## Actual Behavior
This throws an error saying "The following developer has already been invited to the team: 'developer_email@abc.com'."

## Expected Behavior
A member should be allowed to receive multiple invitations, irrespective of he accepts/rejects the invitation.

## Version Info
1.18

**Comment by arunz6161** [comment] 2020-11-17 19:20
Could be a duplicate of #517

**Closed as completed** 2020-12-03 20:37 UTC
Labels: bug
