### ISSUE TITLE
Unable to use field_api_product in apigee maven smartdoc plugin

### ISSUE THREAD

**Issue by OShaikhDevOps** [apigee/apigee-edge-drupal#856] opened 2023-06-12 11:08 UTC
Version:
`apigee-smartdocs-maven-plugin-2.2.3
`
Config File:
```
pom.xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
            <groupId>apigee</groupId>
            <artifactId>parent-pom</artifactId>
            <version>1.0</version>
            <relativePath>shared-pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>Apigee</groupId>
    <artifactId>DeveloperPortal</artifactId>
    <version>1.0</version>
    <name>DeveloperPortal</name>
    <packaging>pom</packaging>
    <profiles>
    <profile>
        <id>dev</id>
        <properties>
        	<portal.url>${purl}</portal.url><!-- URL of the developer portal. -->
        	<portal.username>${pusername}</portal.username><!-- Username for the developer portal. -->
        	<portal.password>${ppassword}</portal.password><!-- Password for the developer portal. -->
        	<portal.format>yaml</portal.format><!-- Format of the OpenAPI specs. json|yaml -->
        	<portal.api.doc.format>basic_html</portal.api.doc.format><!-- Format in the portal. Values: basic_html, restricted_html, full_html -->
        	<portal.directory>./specs</portal.directory> <!-- Directory where OpenAPI specs are accessible. Using ./specs for sample -->
        	<apigee.smartdocs.config.file>./apicatalog-config.json</apigee.smartdocs.config.file> <!-- Config for fields -->
        </properties>
    </profile>
</profiles>
</project>
```
Command Execution:
`mvn install -Pdev -Dpurl="https://example.com/" -Dpusername="xyz" -Dppassword="xyz" -Dapigee.smartdocs.config.options=create`

Error Code:
```
[ERROR] Failed to execute goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.2.3:apidoc (smartdocs-deploy) on project DeveloperPortal: Execution smartdocs-deploy of goal com.apigee.smartdocs.config:apigee-smartdocs-maven-plugin:2.2.3:apidoc failed: Update failure:
[ERROR] Status code: 422
[ERROR] Status Message: Unprocessable Entity
[ERROR] Detailed Message: The following relationship fields were provided as attributes: [ field_api_product ]
```

**Comment by osmanshaikhSystemsltd** [comment] 2023-06-12 11:12
pom.xml file [config file]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
            <groupId>apigee</groupId>
            <artifactId>parent-pom</artifactId>
            <version>1.0</version>
            <relativePath>shared-pom.xml</relativePath>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <groupId>Apigee</groupId>
    <artifactId>DeveloperPortal</artifactId>
    <version>1.0</version>
    <name>DeveloperPortal</name>
    <packaging>pom</packaging>
    <profiles>
    <profile>
        <id>dev</id>
        <properties>
        	<portal.url>${purl}</portal.url>
        	<portal.username>${pusername}</portal.username>
        	<portal.password>${ppassword}</portal.password>
        	<portal.format>yaml</portal.format>
        	<portal.api.doc.format>basic_html</portal.api.doc.format>
        	<portal.directory>./specs</portal.directory> 
        	<apigee.smartdocs.config.file>./apicatalog-config.json</apigee.smartdocs.config.file> 
        </properties>
    </profile>
</profiles>
</project>

**Comment by shishir-intelli** [comment] 2023-07-10 12:31
@osmanshaikhSystemsltd ,
This issue is being tracked in https://github.com/apigee/apigee-edge-drupal/issues/878,
Created PR #879 to fix the `field_api_product` issue for Drupal portal.

Closing this issue now, duplicate of #878

**Closed as completed by shishir-intelli** 2023-07-10 12:31 UTC
Labels: enhancement
