### ISSUE TITLE
Inviting user to team, email address is case sensitive

### ISSUE THREAD

**Issue by yenoomluap** [apigee/apigee-edge-drupal#593] opened 2021-06-11 15:12 UTC
## Description
If inviting a user to a team, the email address is case sensitive (must match was is registered).  If I invite user with their registered email address of user `john.smith@acme.com`, the user would be able to accept the invitation.
If I invite the same user, but use email address like `John.Smith@acme.com`, portal recognizes this as a different user, and will give 403 forbidden page.

## Steps to Reproduce
1. Have user registered with email address 
2. Send invite to user, but change email address case
3. Have user sign into portal
4. Have user click accept link from email
5. User receives 403

## Actual Behavior
User receives 403

## Expected Behavior
I expect the user to be able to accept/decline the invitation, irrespective of the character case used in the email address for the invitation.

## Version Info
1.23

**Comment by phdhiren** [comment] 2021-06-14 05:02
It seems that the issue is with Drupal core - https://www.drupal.org/project/drupal/issues/2490294

**Comment by yenoomluap** [comment] 2021-06-14 16:37
@phdhiren could you advise which patch we would implement for MySQL?  [Would it be comment #37?](https://www.drupal.org/project/drupal/issues/2490294#comment-13968915)

**Comment by phdhiren** [comment] 2021-07-27 14:37
@yenoomluap We cannot recommend specific patch since it is Drupal core. I will close this issue for now as its more of Drupal core then Apigee edge, but if you need further assistance regarding this, please feel free to reopen it.

**Comment by phdhiren** [comment] 2021-07-29 14:48
Reopening the issue.
Let's discuss - What other solution can be when the issue with Drupal core.

**Closed as completed** 2021-10-06 01:17 UTC
Labels: bug, no-issue-activity

**Comment by yenoomluap** [comment] 2022-11-03 20:05
Hello,

We have updated a line in the edge module which fixes this issue.  Please reach out to discuss. @phdhiren 
location:

apigee_edge\modules\apigee_edge_teams\src\Form\AddTeamMembersForm.php

from:
`$emails = array_map('trim', explode(',', $form_state->getValue('developers', '')));
`

to:
`$emails = array_map('trim', explode(',', mb_strtolower($form_state->getValue('developers', ''))));`



Thank you

**Comment by phdhiren** [comment] 2022-11-11 12:21
@yenoomluap 
I've checked the patch does not solve the issue for all i.e. If the users who have Capital letters in email. It may have worked in other cases like yours. 
It seems there is traction in the original Drupal core issue.
