### ISSUE TITLE
Uncaught PHP Exception TypeError ...  /apigee_edge/src/Entity/Developer.php line 526

### ISSUE THREAD

**Issue by Cleets** [apigee/apigee-edge-drupal#1048] opened 2024-03-21 18:54 UTC
## Description
When modifying a user profile in any way we are getting 
Uncaught PHP Exception TypeError: "Drupal\apigee_edge\Entity\Developer::getCacheMaxAge(): Return value must
be of type int, null returned" at  /var/www2/devportalsandbox/web/modules/contrib/apigee_edge/src/Entity/Developer.php line 526" while reading response header from upstream, 

The code at that point is:
  public function getCacheMaxAge(): int {
    return \Drupal::config('apigee_edge.developer_settings')->get('cache_expiration');  
 }

In our configuration, this function is returning NULL .

## Apigee Info
We are using Apigee Edge 3.0.6

## Steps to Reproduce
1. modify a user record within the 'people' view and attempt to save it.
2. without these values set, you will get a white screen and the user's profile will not be saved.

**Comment by kedarkhaire** [comment] 2024-03-22 06:10
Hi @Cleets 

Thanks for sharing the details here.
I tried with saving user record in the People's page (admin/people), I didn't got any error.

In 2nd step you have mentioned, without these values set, we get WSOD and the user record is not saved, here we are not sure of the values you are mentioning.

Can you please share the steps with proper user journey, where you face this issue,
Do also let us know, if you are using default cache_expiration provided by the module or modified to some other value.

Thanks!

**Comment by Cleets** [comment] 2024-03-22 16:32
Thanks for hte response ... let me put the updates in here on Sunday.  
Our QA is usinghte environment right now and I've temporarily worked around the issue by forcing the 
getCacheMaxAge() function to return -1 .

But I can recreate the issue by the end of the weekend.
Cheers,

**Comment by kedarkhaire** [comment] 2024-06-05 14:12
Hi @Cleets 
Its been more than 1 month, we assume that the issue is not reproducible, closing this issue for now. In future, you are facing the same, feel free to reopen this issue by mentioning the steps and versions used.
Thanks!

**Closed as completed by kedarkhaire** 2024-06-05 14:12 UTC
Labels: bug
