### ISSUE TITLE
Expired team invitations should not be actionable.

### ISSUE THREAD

**Issue by jannakha** [apigee/apigee-edge-drupal#498] opened 2020-10-01 03:32 UTC
**v8.x-1.16** 

## Description
Expired team invitation has "Accept" as an option. 
- Clicking on it results on "your invitation has expired" screen.

Expired team invitation has "Decline" as an option. 
- Clicking on it results on "your invitation has expired" screen.

## Steps to Reproduce
0. Unset invitation expiration time (or set to zero)
1. As a team admin - Send invitation to an existing user to join a team
2. As a user - Go to My account -> Invitations tab
it displays expired invitation

## Actual Behavior
Expired team invitation has "Accept" as an option. 
- Clicking on it results on "your invitation has expired" screen.

Expired team invitation has "Decline" as an option. 
- Clicking on it results on "your invitation has expired" screen.

## Expected Behavior
- User should not be able to see option to Accept/Decline if invitation has expired
- User should be able to delete this invitation

**Comment by shadcn** [comment] 2020-10-01 03:39
From the screenshot it looks like the status still says *pending* and not *expired*. Expiration of invitations are handled via cron.

Can you confirm if you have a configured cron? 

(As a test, you can manually run cron to update the status of expired invitations).

**Comment by jannakha** [comment] 2020-10-01 04:56
Yep, I can confirm cron changes invitation status to expired and expired invitations are removed from user's view.

I have another issue with expired invitations:
- When admin re-sends expired invitation, invitee gets error "invitation expired" when they're trying to accept - even though it has a new expiration date.
- After clearing cache user was able to accept this invitation.

Can you please check there's no caching of invitations? That should not relate to cron issue.

**Comment by shadcn** [comment] 2020-10-01 05:30
I can confirm this bug. Let's create a new issue to track this. Thanks @jannakha

**Comment by shadcn** [comment] 2020-10-01 05:33
@jannakha I created https://github.com/apigee/apigee-edge-drupal/issues/500

I'm going to close this one.

We are going to cover the cron setup in documentation.

Thanks for your help testing and improving the module. Appreciate it.

**Closed as completed by shadcn** 2020-10-01 05:33 UTC
Labels: bug
