### ISSUE TITLE
Fatal Error:  contains 1 abstract method and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by kuralarasan** [apigee/apigee-edge-drupal#314] opened 2019-12-23 08:22 UTC
While upgrading from D8.7 to 8.8 following error is occurred. 

**Fatal error:**  Class Drupal\apigee_edge\Entity\Storage\DeveloperAppStorage contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Drupal\Core\Entity\EntityTypeListenerInterface::onFieldableEntityTypeCreate) in \modules\contrib\apigee_edge\src\Entity\Storage\DeveloperAppStorage.php on line 39

**Comment by kscheirer** [comment] 2020-01-06 19:12
I ran into this problem as well. It turned out that composer thinks D8.8 is only compatible with an early version of apigee_edge module, instead of the current one.

There should be an official release soon, once it's verified there are no other problems using D8.8.

Until that happens, the quick and dirty solution is to `composer require "drupal/core": "8.8.x-dev as 8.7.x-dev"`. This allows 8.8 to pretend to also be an 8.7 branch, and therefore 8.8 is compatible with the latest apigee_edge module.

**Comment by cnovak** [comment] 2020-01-07 20:12
I also ran into this today setting up a new site using the new [drupal/recommended-project](https://www.drupal.org/docs/develop/using-composer/using-composer-to-install-drupal-and-manage-dependencies#s-using-drupalrecommended-project) composer template instead of Apigee Kickstart.

Like @kscheirer mentioned, Composer found an old Apigee Edge version that allowed Drupal Core to be > 8.7:

```
% composer info drupal/apigee_edge

name     : drupal/apigee_edge
...
versions : * 1.0.0-rc4
...
```

We plan to release 8.8.0 compatible versions of our modules this week, but in the meantime you can follow @kscheirer 's solution of running `composer require "drupal/core": "8.8.x-dev as 8.7.x-dev"`.  Once we release [Apigee Edge 8.x-1.4](https://github.com/apigee/apigee-edge-drupal/milestone/7?closed=1) . make sure to revert this change.

I will close this ticket, but add a comment if anything else is needed and we will reopen.

## Steps to reproduce
1.  `composer create-project --prefer-dist drupal/recommended-project`
2.  `composer require drupal/apigee_edge`

**Closed as completed by cnovak** 2020-01-07 20:12 UTC
Labels: support request

**Comment by cnovak** [comment] 2020-01-07 21:28
Update: I closed this before looking into this more - I don't think @kscheirer 's solution above will work since the Apigee Edge module needs changes to be compatible with Drupal core 8.8.x.  I fixed the error by bringing down the dev version of the codebase that has the changes:

1. Update the main project composer.json adding a new "vcs" section for Apigee Edge GitHub project:
```
 "repositories": [
       ...
        {
            "type": "vcs",
            "url": "git@github.com:apigee/apigee-edge-drupal.git"
        }
    ],
```
2. Update the main project's composer.json file to require the 8.x-1.x branch of Apigee Edge:
```
composer require drupal/apigee_edge dev-8.x-1.x  
```

However, you will be using the development branch of Apigee Edge module, and should switch back to using a release version for production use.  I would recommend waiting until we release Apigee Edge 8.x-1.4 that is compatible with Drupal core 8.8.x.
