### ISSUE TITLE
Analytic reports not working with hybrid-enabled orgs

### ISSUE THREAD

**Issue by apickelsimer** [apigee/apigee-edge-drupal#552] opened 2021-01-25 17:13 UTC
## Description
I am receiving an error on the analytics page for a hybrid-enabled org

## Steps to Reproduce
1. Go to '/user/{user}/apps/{app}/analytics

## Actual Behavior
An error is displayed in the UI "Unable to retrieve analytics data. Please try again." If you check the logs, you will see the following:

`{
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"_optimized\": Cannot bind query parameter. Field 'optimized' could not be found in request message.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "description": "Invalid JSON payload received. Unknown name \"_optimized\": Cannot bind query parameter. Field 'optimized' could not be found in request message."
          }
        ]
      }
    ]
  }
}`

## Expected Behavior
The page should display the analytics data as expected. 

## Notes
The request parameters to fetch analytics for the management API have changed and no longer support '_optimized' as a query parameter. Please refer to the new API definition found at: https://cloud.google.com/apigee/docs/reference/apis/apigee/rest/v1/organizations.environments.stats/get

## Version Info
apigee_edge: 8.x-1.9
Drupal: 8.8.10
PHP: 7.2.34

**Comment by mxr576** [comment] 2021-01-25 20:57
This is a duplicate of https://github.com/apigee/apigee-edge-drupal/issues/481 and https://github.com/apigee/apigee-client-php/issues/105.

**Comment by phdhiren** [comment] 2021-03-02 06:50
Resolved with https://github.com/apigee/apigee-client-php/pull/123

**Closed as completed by phdhiren** 2021-03-02 06:50 UTC
Labels: bug
