### ISSUE TITLE
Getting Apigee\Edge\Exception\ApiRequestException: cURL error 7: when trying to connect to Apigee Edge OPDK v4.52.00 from Drupal 9.5

### ISSUE THREAD

**Issue by mnimakwala** [apigee/apigee-edge-drupal#1064] opened 2024-06-28 16:33 UTC
Hi All,

I am getting below error when trying to connect to Apigee Edge OPDK 4.52.00 from Drupal 9.5 version.
apigee_edge Error
Apigee\Edge\Exception\ApiRequestException: cURL error 7: (see https://curl.haxx.e/libcurl/c/libcurl-errors.html) in Apigee\Edge\HttpClient\Plugin\ResponseHandlerPlugin->Apigee\Edge\HttpClient\Plugin\{closure}() (line 73 of /var/www/html/.../vendor/apigee/apigee-client-php/src/HttpClient/Plugin/ResponseHandlerPlugin.php).

apigee_edge_debug Error
GET /v1/organizations/---uat HTTP/1.1
>>>>>>>>
GET /v1/organizations/---uat HTTP/1.1
X-Apigee-Edge-Api-Client-Profiler: X-Apigee-Edge-Api-Client-Profiler
Host: hotsname:portnumber
User-Agent: Apigee Edge/2.1.4, Drupal/9.5.11 (Apigee Edge PHP Client/2.1.4; PHP/8.2.13)
Accept: application/json; charset-utf-8
Authorization: Basic ..........................................

apigee_edge_debug Error
GET /computeMetadata/v1/instance/service-accounts/default/token HTTP/1.1
>>>>>>>>
GET /computeMetadata/v1/instance/service-accounts/default/token HTTP/1.1
X-Apigee-Edge-Api-Client-Profiler: X-Apigee-Edge-Api-Client-Profiler
Host: metadata.google.internal
User-Agent: Apigee Edge/2.1.4, Drupal/9.5.11 (Apigee Edge PHP Client/2.1.4; PHP/8.2.13)
Accept: application/json; charset-utf-8
Metadata-Flavor: Google

Could you please guide me in resolving this issue?

Thanks,
Mustufa

**Comment by kedarkhaire** [comment] 2024-06-28 19:10
Hi Mustufa,

Seems you are having connection issue.

Can you please check connection using a curl call ?

`https://host:port/v1/organizations/{org_name}`

Authorize it with the above mentioned Basic authorization, also I am removing the mentioned partial creds.

Also try to upgrade site to the latest version. 

Thanks!

**Comment by mnimakwala** [comment] 2024-06-29 11:10
Hi Kedar,

Thanks for you support! Much appreciated!
I have checked running command (https://host:port/v1/organizations/{org_name}) and found that it is not working with the generic user we have created having drupalportal role for connecting to Apigee Edge. But it is working with other users having Organization Administrator role assigned.  Looks like drupalportal role is not created corrected. Looks like role creation is not done correctly.

So I have tried with user having Organization Administrator role assigned to it and found the same issue. (as mentioned in my original query) in watchdog-show.

Please advise.

Thanks,
Mustufa

**Comment by mnimakwala** [comment] 2024-07-01 05:45
Hi Team,

Any update on this please. This is a showstopper for us and hence unable to proceed further.
Let me know if any more details are required.

Thanks,
Mustufa

**Comment by shishir-intelli** [comment] 2024-07-01 06:22
Hi @mnimakwala ,

We are looking into this issue, 
In the meantime, could you please check the documentation below
https://www.drupal.org/docs/contributed-modules/apigee-edge/configure-the-connection-to-apigee#configure-credentials-edge 
to ensure you have configured the Drupal portal according to the instructions in the doc for connecting to Apigee Edge private cloud.

**Comment by kedarkhaire** [comment] 2024-07-25 15:02
Hi @mnimakwala 
Can you please update here, if the above documentation helped you or are you still facing issue with the generic user created?

Thanks!

**Comment by kedarkhaire** [comment] 2024-08-13 14:23
Hi @mnimakwala Closing this issue as there is no reply on the above query from long time, considering the solution worked for you. Feel free to reopen the issue, if the issue is still there with the details.
Thanks!

**Closed as completed by kedarkhaire** 2024-08-13 14:23 UTC
