### ISSUE TITLE
Relying on entity queries to check access by default is deprecated

### ISSUE THREAD

**Issue by divya-intelli** [apigee/apigee-edge-drupal#841] opened 2023-05-26 08:58 UTC
## Is your feature request related to a problem? Please describe.
Relying on entity queries to check access by default is deprecated in drupal:9.2.0 and an error will be thrown from drupal:10.0.0. Call \Drupal\Core\Entity\Query\QueryInterface::accessCheck() with TRUE or FALSE to specify whether access should be checked 

**Files affected :**
modules/contrib/apigee_edge/modules/apigee_edge_teams/src/Controller/TeamApp
KeysController.php
modules/contrib/apigee_edge/modules/apigee_edge_teams/src/Entity/Storage/Tea
mInvitationStorage.php
modules/contrib/apigee_edge/modules/apigee_edge_teams/src/ParamConverter/Tea
mAppNameConverter.php
modules/contrib/apigee_edge/src/Controller/DeveloperAppKeysController.php
modules/contrib/apigee_edge/src/Entity/Storage/DeveloperAppStorage.php
modules/contrib/apigee_edge/src/ParamConverter/DeveloperAppNameConverter.php
modules/contrib/apigee_edge/tests/src/Functional/DeveloperAppUITestTrait.php 
modules/contrib/apigee_edge/tests/src/Functional/DeveloperAppUITestTrait.php
modules/contrib/apigee_edge/tests/src/Functional/QueryTest.php

## Additional context 
https://www.drupal.org/node/3201242

**Comment by mxr576** [comment] 2023-05-30 12:44
Is this a duplicate of #783? :thinking:

**Comment by divya-intelli** [comment] 2023-05-30 14:14
@mxr576 , the mentioned files are not covered in #783. Also wanted to keep separate PRs as we have added Vladimir as co-author in #783.

**Closed as completed** 2023-06-15 06:40 UTC
Labels: enhancement, Drupal 10 Preparation
