### ISSUE TITLE
product_access_control` placeholder field

### ISSUE THREAD

**Issue by epowelljr** [apigee/apigee-edge-drupal#214] opened 2019-06-05 02:44 UTC
Do you know how to resolve this displaying in the Status Report of Drupal 8.7.2

ENTITY/FIELD DEFINITIONS
Mismatched entity and/or field definitions
The following changes were detected in the entity type and field definitions.
API Doc
The `product_access_control` placeholder field needs to be installed.

**Comment by jacine** [comment] 2019-06-05 14:49
I believe this is related to Apigee Edge, so I've transferred your report.  @epowelljr can you please provide more information?  If you could please use this template in doing so, it'd be helpful:

```md
| Q                           | A
| --------------------------- | -----------------------------------------------
| Bug?                        | no|yes
| New Feature?                | no|yes
| Module Version              | Version or commit SHA <br> This can be the version you can see on admin/modules in Drupal or the output of this command: <code>composer show | grep drupal/apigee_edge | awk '{if ($2 ~ "dev$") print $2 " "$3; else print $2;}'</code>
| PHP Client version          | Version or commit SHA <br> This can be the output of this command: <code>composer show | grep apigee/apigee-client-php | awk '{if ($2 ~ "dev$") print $2 " "$3; else print $2;}'</code>
| Requires PHP client fix     | no|link to an Apigee Client PHP library issue or pull request

#### Actual Behavior

What is the actual behavior?


#### Expected Behavior

What is the behavior you expect?


#### Steps to Reproduce the behavior

What are the steps to reproduce this bug? Please add code examples,
screenshots or links to GitHub repositories that can demonstrate the problem.


#### Proposed Solution

If you have already ideas how to solve the issue please describe it here.
(Remove this section if it is not needed.)
```

Thank you.

**Comment by jacine** [comment] 2019-06-05 15:04
I also wanted to note that I'm unable to reproduce this within Kickstart, using Apigee Edge 1.0. The status report shows that everything is up to date:

<img width="377" alt="Screen Shot 2019-06-05 at 11 00 10 AM" src="https://user-images.githubusercontent.com/60979/58966890-1b4be380-8781-11e9-94c5-4869f7e07064.png">

**Comment by jacine** [comment] 2019-06-05 17:07
@epowelljr Hi, we just realized you are using an older version of Apigee Edge, and likely kickstart.  This functionality has been moved to a new module, https://www.drupal.org/project/apigee_api_catalog. 
You should run `composer update --optimize-autoloader --with-dependencies` and reinstall.

If you have any issues with this, please let us know.

**Closed as completed** 2019-06-05 17:07 UTC
