### ISSUE TITLE
App key display remains non-responsive  and Key copy button don't work after appgroup upgrade on  drupal-9  portal

### ISSUE THREAD

**Issue by kpatolia1** [apigee/apigee-edge-drupal#933] opened 2023-09-11 14:59 UTC
## Description
After Drupal upgrade on appgroup  with apigee version 2.1.1  app key copy and display stops working.
## Apigee Info
ApgeeX
## Steps to Reproduce
1. Go to '.Teamapps..'
2. Click on '..Add Keys..'
3. Click on display icon  

## Actual Behavior
Button have no response
## Expected Behavior
It should open with display of key client or key secret
## Screenshots
Screenshot attached
## Notes
It seems some conflict on javascript or Jquery version issue.

## Version Info
Drupal 9.5.10
PHP 8.1.23
apigee_edge: version 2.1.1

**Comment by shishir-intelli** [comment] 2023-09-12 05:00
Hi @kpatolia1 
We are not able to reproduce this error,
Could you please send us the error from web console for javascript.

Meanwhile, also can you clear the cache of the site and check again (_drush cache-rebuild_).

**Comment by kpatolia1** [comment] 2023-09-15 00:56
Hi @shishir-intelli , 
I have attached the screenshot of inspector here , basically ajax call is bringing the result but js is conflicting and its not displaying  it.



<img width="1289" alt="Screenshot 2023-09-15 at 8 11 40 AM" src="https://github.com/apigee/apigee-edge-drupal/assets/144493596/a8f2f787-9a62-423c-934f-bd9ec87ab2c2">

**Comment by shishir-intelli** [comment] 2023-09-15 13:25
@kpatolia1 ,
If there is any error on `console` tab, could you also please share us screenshot of same.

Please run the command `composer show` and share us the output list.

**Comment by shishir-intelli** [comment] 2023-09-27 06:16
Hope this issue has been resolved.
Closing this issue, feel free to re-open for any further help.

**Closed as completed by shishir-intelli** 2023-09-27 06:16 UTC
Labels: bug
